[icons]
# font awesome
firefox = "ï‰©"
Google-chrome = "ï‰¨"
Alacritty = "ï„ "
thunderbird = "ïƒ "
URxvt = "ï„ "
Gpick = "ï”¿"
Nautilus = "ğŸ“˜"
ranger = "ï…›"
Evince = "ï‡"
Gvim = "ï„¡"
Gitk = "ï‡“"
Spotify = "ï†¼"
Zathura = "#"
foot = "ï„ "

[aliases]

[general]
default_icon = "ï„‘"
wm_property = "class"

[options]
remove_duplicates = true
no_names = false
no_icon_names = true
